name: Deploy to EC2 via AWS SSM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Trigger SSM deploy command on EC2
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --comment "GitHub Deploy Trigger" \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --parameters commands="cd ~/flask-ec2-api && git pull origin main && sudo systemctl restart flask-api" \
            --output text
